project:
  type: book
  output-dir: docs

book:
  title: "Multiome Pre-processing for Zebrafish"
  subtitle: "Dartmouth Genomic Data Science Core"
  author: "Mike Martinez M.S."
  date: today
  repo-url: https://github.com/Dartmouth-Data-Analytics-Core/zebrafish-multiome-vignette
  repo-actions: [edit, issue, source]
  search: true
  sidebar:
    style: floating
    logo: cqb_logo.jpg
    collapse-level: 2
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-Building-GRanges-Reference.qmd
    - 03-RNA-preprocessing-and-QC.qmd

format:
  html:
    theme:
      light: [litera, cqb.scss]
      dark: [darkly, cqb.scss]
    css: styles.css
    toc: true
    toc-depth: 3
    toc-title: "On this page"
    code-copy: true
    code-overflow: wrap
    code-link: true
    fig-align: center
    link-external-newwindow: true

execute:
  freeze: auto
  echo: true
  warning: false

editor: visual
